version: "3.9"

services:
  flaskapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=main.py   # or 'website' if you're using an app factory
      - FLASK_ENV=development
